name: 发布到GitCode

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'GitHub Action Run ID to download artifacts from'
        required: true
        type: string

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Download artifacts from specified run
      id: download
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUN_ID: ${{ github.event.inputs.run_id }}
      run: |
        echo "Checking artifacts for run ID: $RUN_ID"
        
        # Get artifacts list for the specified run
        artifacts_response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts")
        
        # Check if there are any artifacts
        artifacts_count=$(echo "$artifacts_response" | jq '.total_count')
        
        if [ "$artifacts_count" -eq 0 ]; then
          echo "No artifacts found for run ID: $RUN_ID"
          echo "has_artifacts=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "Found $artifacts_count artifact(s)"
        echo "has_artifacts=true" >> $GITHUB_OUTPUT
        
        # Create downloads directory
        mkdir -p ./downloads
        
        # Download all artifacts
        echo "$artifacts_response" | jq -r '.artifacts[] | "\(.id) \(.name)"' | while read artifact_id artifact_name; do
          echo "Downloading artifact: $artifact_name (ID: $artifact_id)"
          
          # Download artifact
          curl -L -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id/zip" \
            -o "./downloads/${artifact_name}.zip"
            
          echo "Downloaded: ${artifact_name}.zip"
        done
        
    - name: Process and upload artifacts to GitCode
      if: steps.download.outputs.has_artifacts == 'true'
      env:
        GITCODE_PAT: ${{ secrets.GitCodePAT }}
        GITCODE_REPO: https://gitcode.com/maotoumao/MusicFreeDesktopRelease.git
        GIT_USER_NAME: maotoumao
        GIT_USER_EMAIL: lhx_xjtu@163.com
      run: |
        # Configure git
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_USER_EMAIL"
        
        # Clone the GitCode repository
        echo "Cloning GitCode repository..."
        git clone https://$GIT_USER_NAME:$GITCODE_PAT@gitcode.com/maotoumao/MusicFreeDesktopRelease.git gitcode-repo
        cd gitcode-repo
        
        # Get current date for commit message
        CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')
        
        # Process artifacts
        cd ../downloads
        
        for zip_file in *.zip; do
          if [ ! -f "$zip_file" ]; then
            continue
          fi
          
          echo "Processing: $zip_file"
          
          # Create a directory for this artifact
          artifact_dir="${zip_file%.zip}"
          mkdir -p "$artifact_dir"
          
          # Extract the artifact zip
          unzip -q "$zip_file" -d "$artifact_dir"
          
          # Process files in the extracted directory
          for file in "$artifact_dir"/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              echo "Processing file: $filename"
              
              # Check if filename contains "portable"
              if [[ "$filename" == *"portable"* ]]; then
                echo "File contains 'portable', uploading zip directly: $filename"
                # Copy portable zip file directly to GitCode repo
                cp "$file" "../gitcode-repo/$filename"
              else
                echo "File does not contain 'portable', checking if it's a zip/archive: $filename"
                
                # Check if it's a zip file and extract it
                if [[ "$filename" == *.zip ]]; then
                  echo "Extracting and uploading contents of: $filename"
                  extract_dir="${filename%.zip}_extracted"
                  mkdir -p "$extract_dir"
                  unzip -q "$file" -d "$extract_dir"
                  
                  # Copy all extracted files to GitCode repo
                  for extracted_file in "$extract_dir"/*; do
                    if [ -f "$extracted_file" ]; then
                      extracted_filename=$(basename "$extracted_file")
                      echo "Copying extracted file: $extracted_filename"
                      cp "$extracted_file" "../gitcode-repo/$extracted_filename"
                    fi
                  done
                  
                  # Clean up extraction directory
                  rm -rf "$extract_dir"
                else
                  echo "Copying file directly: $filename"
                  # Copy non-zip files directly to GitCode repo
                  cp "$file" "../gitcode-repo/$filename"
                fi
              fi
            fi
          done
          
          # Clean up artifact directory
          rm -rf "$artifact_dir"
        done
        
        # Commit and push to GitCode
        cd ../gitcode-repo
        
        # Add all files
        git add .
        
        # Check if there are any changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Committing and pushing changes to GitCode..."
          git commit -m "Update release artifacts - $CURRENT_DATE"
          git push --force origin master
          echo "✅ Successfully pushed artifacts to GitCode"
        fi
        
    - name: Cleanup
      if: always()
      run: |
        rm -rf ./downloads
        rm -rf ./gitcode-repo
        
    - name: Summary
      run: |
        if [ "${{ steps.download.outputs.has_artifacts }}" == "true" ]; then
          echo "✅ Artifacts processed and pushed to GitCode successfully"
        else
          echo "ℹ️ No artifacts found for the specified run ID"
        fi
